const {chromium}=require('playwright'),assert=require('assert/strict'),fs=require('fs'),path=require('path'),http=require('http');
(async()=>{
 const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>{const u=decodeURIComponent(req.url.split('?')[0]),f=path.join(root,u==='/'?'index.html':u);try{res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.html')?'text/html':f.endsWith('.svg')?'image/svg+xml':'application/octet-stream');res.end(fs.readFileSync(f))}catch{res.statusCode=404;res.end()}});await new Promise(r=>server.listen(8802,'127.0.0.1',r));
 const browser=await chromium.launch({args:['--no-sandbox']}),p=await browser.newPage({viewport:{width:390,height:844},timezoneId:'Asia/Tehran',serviceWorkers:'allow'}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto('http://127.0.0.1:8802');await p.waitForSelector('#loading-screen',{state:'detached'});
 await p.evaluate(()=>{S=DS();S.onboarding={stage:'done'};S.lang='fa';S.cal='j';S.myname='برنامهٔ نمونه';S.theme='light';S.accent='fox';S.wps=[{id:'w1',name:'اورژانس نمونه',color:'#ea8430',codes:decCodes(DEF.map(x=>x.join('|')).join('\n'))}];const w=S.wps[0];cm=fromJ(1405,7,1);sel=iso(fromJ(1405,7,14));S.shifts=calendarDays(cm).filter(Boolean).map((d,i)=>{const date=iso(d),text=['D','E','N','-','-','DE','M','D','-','E'][i%10];return {id:'h'+date,wp:w.id,date,text,segs:makeSegs(date,parse(w,text))}});S.mates=Array.from({length:120},(_,i)=>({id:'m'+i,wp:w.id,name:['علی رضایی','سارا احمدی','مریم محمدی','حسن کریمی'][i%4]+' '+(i+1),cells:Object.fromEntries(S.shifts.map(h=>[h.date,i===119&&h.date===sel?'S':i%3===0?'D':i%3===1?'E':'-'])),uns:[],page:Math.floor(i/20)+1}));S.mates[119].cells[iso(fromJ(1405,7,13))]='D';S.mates[119].cells[iso(fromJ(1405,7,15))]='D';roster={wp:'w1',cm,page:1,wide:false,search:'',returnTab:'agenda',date:sel,shift:'D',hoursPerson:'self'};tab='agenda';vm='month';daySelected=false;render()});
 const initial=await p.evaluate(()=>monthlyHours(cm).creditedMinutes);assert.ok(initial>0);assert.equal(await p.locator('.monthly-hours').count(),1);assert.equal(await p.locator('.monthly-hours').getAttribute('open'),null);
 // Open breakdown, use the normal in-place shift editor, then Undo.
 await p.locator('.monthly-hours>summary').click();assert.ok(await p.locator('.hours-breakdown').isVisible());await p.evaluate(()=>{sel=iso(fromJ(1405,7,14));pick(sel)});await p.getByRole('button',{name:'ثبت / تغییر شیفت',exact:true}).first().click();await p.locator('.shift-key').filter({has:p.locator('bdi', {hasText:/^D$/})}).first().click();await p.locator('#inline-editor').getByRole('button',{name:'ذخیره',exact:true}).click();await p.waitForFunction(()=>!changeSaving);assert.ok(await p.evaluate(()=>monthlyHours(cm).creditedMinutes>0));assert.equal(await p.locator('.monthly-hours[open]').count(),1);await p.evaluate(()=>undoLastChange());assert.equal(await p.evaluate(()=>monthlyHours(cm).creditedMinutes),initial);
 await p.evaluate(()=>{$('#change-feedback').hidden=true;daySelected=false;personalHoursOpen=false;$('.monthly-hours').open=false;render();window.scrollTo(0,0)});await p.screenshot({path:path.join(__dirname,'calendar-light.png')});assert.ok(await p.locator('.month-grid').evaluate(el=>el.getBoundingClientRect().bottom<innerHeight-70),'monthly grid fits ordinary phone');
 await p.evaluate(()=>{S.theme='dark';render();window.scrollTo(0,0)});await p.screenshot({path:path.join(__dirname,'calendar-dark.png')});
 // Every imported colleague is selectable even if search/swap preferences hide them.
 await p.evaluate(()=>openRoster('w1'));await p.locator('.roster-hours>summary').click();assert.equal(await p.locator('#hours-person option').count(),121);await p.locator('#hours-person').selectOption('m119');assert.ok(await p.locator('.hours-breakdown').textContent().then(t=>t.includes('استعلاجی')||t.includes('S')));assert.equal(await p.evaluate(()=>monthlyHours(roster.cm,{workplace:'w1',person:'m119'}).pending),1);
 // Define sick leave credit from the existing symbol editor, then verify recalculation and persistence.
 await p.evaluate(()=>editWp('w1',true));const sick=p.locator('.code-editor').filter({has:p.locator('.code-value[value="S"]')});await sick.locator('summary').click();await sick.locator('.code-hours').selectOption('leave');await p.locator('#dlg').getByRole('button',{name:'ذخیره',exact:true}).click();await p.waitForFunction(()=>!changeSaving);assert.equal(await p.evaluate(()=>monthlyHours(roster.cm,{workplace:'w1',person:'m119'}).pending),0);assert.equal(await p.evaluate(()=>S.wps[0].codes.find(c=>c.code==='S').hoursRole),'leave');
 let layouts=0;for(const width of [320,390])for(const lang of ['fa','en'])for(const theme of ['light','dark'])for(const scale of [100,200])for(const cal of ['g','j']){await p.setViewportSize({width,height:844});await p.evaluate(({lang,theme,scale,cal})=>{S.lang=lang;S.theme=theme;S.cal=cal;cm=mfirst(fromJ(1405,7,14));roster.cm=cm;document.documentElement.style.fontSize=scale+'%';daySelected=false;tab='agenda';vm='month';personalHoursOpen=false;render()},{lang,theme,scale,cal});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`calendar overflow ${width} ${lang} ${theme} ${scale} ${cal}`);await p.locator('.monthly-hours>summary').click();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`calendar breakdown overflow ${width} ${lang} ${theme} ${scale} ${cal}`);await p.evaluate(()=>{tab='roster';rosterHoursOpen=true;render()});assert.equal(await p.locator('#hours-person option').count(),121);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`roster hours overflow ${width} ${lang} ${theme} ${scale} ${cal}`);layouts++}
 await p.setViewportSize({width:390,height:844});await p.evaluate(()=>{S.lang='fa';S.theme='dark';S.cal='j';document.documentElement.style.fontSize='100%';roster.cm=fromJ(1405,7,1);roster.date=iso(fromJ(1405,7,14));roster.hoursPerson='m0';rosterHoursOpen=true;render();$('#change-feedback').hidden=true;window.scrollTo(0,0)});await p.screenshot({path:path.join(__dirname,'colleague-hours-dark.png')});
 // Totals survive an offline reload and remain derived from saved definitions/rosters.
 const stored=await p.evaluate(()=>monthlyHours(roster.cm,{workplace:'w1',person:'m119'}).creditedMinutes);await p.evaluate(async()=>{await save();await navigator.serviceWorker.ready});await p.waitForFunction(()=>!!navigator.serviceWorker.controller);await p.context().setOffline(true);await p.reload();await p.waitForSelector('#loading-screen',{state:'detached'});await p.evaluate(()=>{roster.wp='w1';roster.cm=fromJ(1405,7,1);roster.hoursPerson='m119';rosterHoursOpen=true;tab='roster';render()});assert.equal(await p.evaluate(()=>monthlyHours(roster.cm,{workplace:'w1',person:'m119'}).creditedMinutes),stored);assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(__dirname,'hours-results.json'),JSON.stringify({version:'v12.17',layouts,calendarCompact:true,ownEditUndo:true,colleague120:true,symbolRuleSave:true,offlineReload:true,errors},null,2));await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
