const {chromium}=require('playwright'),assert=require('assert/strict'),fs=require('fs'),path=require('path'),http=require('http');
(async()=>{const root=path.resolve(process.env.FOXIORA_APP||path.join(__dirname,'..')),server=http.createServer((req,res)=>{const u=decodeURIComponent(req.url.split('?')[0]),f=path.join(root,u==='/'?'index.html':u);try{res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.html')?'text/html':f.endsWith('.svg')?'image/svg+xml':'application/octet-stream');res.end(fs.readFileSync(f))}catch{res.statusCode=404;res.end()}});await new Promise(r=>server.listen(8801,'127.0.0.1',r));const browser=await chromium.launch({args:['--no-sandbox']}),p=await browser.newPage({viewport:{width:390,height:844},serviceWorkers:'allow'}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto('http://127.0.0.1:8801');await p.waitForSelector('#loading-screen',{state:'detached'});
await p.evaluate(()=>{S=DS();S.onboarding={stage:'done'};S.cal='g';S.myname='برنامهٔ من';S.wps=[{id:'w1',name:'اورژانس نمونه',color:'#3b82f6',codes:decCodes(DEF.map(x=>x.join('|')).join('\n'))},{id:'w2',name:'بخش دوم',codes:decCodes('X|روز کامل|07:30-20:00\n-|off|off')}];const names=['علی رضایی','سارا احمدی','مریم محمدی','حسن کریمی','رضا حسینی','نگار کاظمی','مهسا مرادی','امیر نادری','زهرا عباسی','رها تقوی'];S.mates=['D','E','DE','N','EN','En','-','M','S','E'].map((text,i)=>({id:'m'+i,wp:'w1',name:names[i],cells:Object.fromEntries(Array.from({length:31},(_,j)=>['2099-10-'+String(j+1).padStart(2,'0'),j===14&&i===1?'D':text])),uns:i===9?['2099-10-10']:[],page:Math.floor(i/2)+1}));S.mates[1].swapRules={excluded:true};S.mates.push({id:'other',wp:'w2',name:'همکار بخش دوم',cells:{'2099-10-10':'X'},uns:[]});S.shifts=[{id:'own',wp:'w1',date:'2099-10-10',text:'-',segs:[]}];roster={wp:'w1',cm:new Date('2099-10-01'),page:1,wide:false,search:'',returnTab:'agenda',date:'2099-10-10',shift:'E'};tab='roster';render()});
assert.equal(await p.locator('.presence-person').count(),4);assert.equal(await p.locator('.presence-unclear li').count(),1);assert.equal(await p.locator('.presence-person[data-person=self]').count(),0);assert.equal(await p.locator('.presence-person[data-person=m2] .shift-mark').textContent(),'DE');assert.equal(await p.locator('.presence-person[data-person=other]').count(),0);
const before=await p.evaluate(()=>JSON.stringify(S));await p.locator('#presence-shift').selectOption('N');assert.equal(await p.locator('.presence-person').count(),2);await p.locator('#presence-date').selectOption('2099-10-15');assert.equal(await p.evaluate(()=>roster.page),2);assert.equal(await p.locator('.roster-date[aria-pressed=true]').count(),1);assert.equal(await p.locator('#presence-shift').inputValue(),'N');await p.locator('.roster-date').nth(1).click();assert.equal(await p.locator('#presence-date').inputValue(),'2099-10-16');assert.equal(await p.evaluate(()=>JSON.stringify(S)),before);
await p.locator('#presence-date').selectOption('2099-10-10');await p.locator('#presence-shift').selectOption('E');await p.locator('.roster-search').fill('علی');assert.equal(await p.locator('.roster-table tbody tr').count(),2);assert.equal(await p.locator('.presence-person').count(),4);await p.locator('.roster-search').fill('');
// In-place edits and Undo immediately refresh the same presence section.
await p.locator('.roster-table tbody tr').nth(2).locator('.roster-cell').nth(2).click();assert.equal(await p.locator('#mate-code').inputValue(),'E');await p.locator('#mate-code').fill('D');await p.locator('#inline-editor').getByRole('button',{name:'ذخیره',exact:true}).click();await p.waitForFunction(()=>!changeSaving);assert.equal(await p.locator('.presence-person').count(),3);await p.evaluate(()=>undoLastChange());assert.equal(await p.locator('.presence-person').count(),4);await p.evaluate(()=>{$('#change-feedback').hidden=true});
let layouts=0;for(const width of [320,390])for(const lang of ['fa','en'])for(const theme of ['light','dark'])for(const scale of [100,200])for(const cal of ['g','j']){await p.setViewportSize({width,height:844});await p.evaluate(({lang,theme,scale,cal})=>{S.lang=lang;S.theme=theme;S.cal=cal;roster.date='2099-10-10';roster.cm=mfirst(new Date(roster.date+'T00:00'));roster.page=Math.floor(((cal==='j'?jp(new Date(roster.date+'T00:00')).d:new Date(roster.date+'T00:00').getDate())-1)/7);document.documentElement.style.fontSize=scale+'%';render()},{lang,theme,scale,cal});assert.equal(await p.locator('.presence-person').count(),4);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow ${width} ${lang} ${theme} ${scale} ${cal}`);layouts++}
await p.setViewportSize({width:390,height:844});await p.evaluate(()=>{S.lang='fa';S.cal='g';S.theme='light';document.documentElement.style.fontSize='100%';roster.cm=new Date('2099-10-01');roster.page=1;roster.date='2099-10-10';render();window.scrollTo(0,0)});assert.equal(await p.evaluate(()=>S.shifts[0].text),'-');assert.equal((await p.locator('.self-row .roster-selected-date .roster-cell').textContent()).trim(),'-');await p.screenshot({path:path.join(__dirname,'presence-light.png')});assert.ok(await p.locator('.roster-presence').evaluate(el=>el.getBoundingClientRect().bottom<innerHeight-80));await p.evaluate(()=>{S.theme='dark';render();window.scrollTo(0,0)});await p.screenshot({path:path.join(__dirname,'presence-dark.png')});
// Switching workplace uses that workplace's codes and people only.
await p.locator('select[aria-label="محل کار"]').selectOption('w2');await p.locator('#presence-date').selectOption('2099-10-10');assert.equal(await p.locator('#presence-shift').inputValue(),'X');assert.equal(await p.locator('.presence-person').count(),1);assert.equal(await p.locator('.presence-person').textContent(),'همکار بخش دوم');await p.locator('select[aria-label="محل کار"]').selectOption('w1');await p.locator('#presence-date').selectOption('2099-10-10');await p.locator('#presence-shift').selectOption('E');
// Six pages / 120 matching names: the lookup includes every row, no truncation.
await p.evaluate(()=>{S.shifts=[];S.mates=Array.from({length:120},(_,i)=>({id:'p'+i,wp:'w1',name:'همکار نمونه '+(i+1),cells:{'2099-10-10':'E'},uns:[],page:Math.floor(i/20)+1}));roster.date='2099-10-10';roster.shift='E';render()});assert.equal(await p.locator('.presence-person').count(),120);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.equal(await p.locator('.presence-person[data-person=p119]').count(),1);
// Use stored data only: navigate, reload and query while offline.
await p.evaluate(async()=>{await save();await navigator.serviceWorker.ready});await p.waitForFunction(()=>!!navigator.serviceWorker.controller);await p.context().setOffline(true);await p.reload();await p.waitForSelector('#loading-screen',{state:'detached'});await p.evaluate(()=>{roster.wp='w1';roster.cm=new Date('2099-10-01');roster.date='2099-10-10';roster.page=1;roster.shift='E';openRoster('w1')});assert.equal(await p.locator('.presence-person').count(),120);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'presence-results.json'),JSON.stringify({version:'v12.16',layouts,offUser:true,noPersonalSchedule:true,combinedDuty:true,allPages:true,all120Names:true,unclearSeparate:true,workplaceScope:true,searchIndependent:true,readOnly:true,editUndo:true,dateHeader:true,dateWeekSync:true,offlineReload:true,errors},null,2));await browser.close();server.close()})().catch(e=>{console.error(e);process.exit(1)});
