const {test}=require('node:test'),assert=require('node:assert/strict'),{app}=require('./support.cjs');
function seed(){const a=app();a.run(`var w=S.wps[0],date='2099-10-20';S.shifts=[{id:'d',wp:w.id,date,text:'D',segs:makeSegs(date,parse(w,'D'))}];S.mates=[{id:'m',wp:w.id,name:'همکار',cells:{[date]:'-','2099-10-19':'-','2099-10-21':'-'},uns:[]}];tc.wp=w.id;tc.dates=['d'];`);return a}
function pattern(a){a.run(`S.mates[0].cells=Object.fromEntries(Array.from({length:30},(_,i)=>[rosterDate('2099-10-01',i),i%3===0?'-':'D']));S.mates[0].cells[date]='-'`);return a}
test('manual exclusion filters direct cover, reciprocal swaps and common cover with a readable reason',async()=>{const {run,runAsync}=seed();run('S.mates[0].swapRules={excluded:true}');assert.equal(run('coverCalc().rows[0].free.length'),0);assert.equal(run('coverCalc().all.length'),0);assert.equal(run('coverCalc().rows[0].blocked[0].reason'),'preference');assert.match(run('swapReason(coverCalc().rows[0].blocked[0])'),/کنار گذاشته/);assert.equal(run('reciprocalSwaps(w,S.shifts[0],S.mates[0]).swaps.length'),0)});
test('accepted full codes do not permit DE when a D-only colleague already has E',async()=>{const {run,runAsync}=seed();run("S.mates[0].cells[date]='E';S.mates[0].swapRules={allowed:['D']}");assert.equal(run('coverCalc().rows[0].ext.length'),0);assert.equal(run('coverCalc().rows[0].blocked[0].reason'),'preference');run("S.mates[0].swapRules.allowed=['DE']");assert.equal(run('coverCalc().rows[0].ext[0].combo'),'DE')});
test('no-combined rejects DE but still permits an ordinary D on an off date',async()=>{const {run,runAsync}=seed();run("S.mates[0].swapRules={noCombined:true};S.mates[0].cells[date]='E'");assert.equal(run('coverCalc().rows[0].ext.length'),0);run("S.mates[0].cells[date]='-'");assert.equal(run('coverCalc().rows[0].free.length'),1)});
test('maximum length checks merged handover duration and custom long atomic codes',async()=>{const {run,runAsync}=seed();assert.equal(run("dutyHours(makeSegs(date,parse(w,'DE')))"),12.5);run("S.mates[0].swapRules={maxHours:12};S.mates[0].cells[date]='E'");assert.equal(run('coverCalc().rows[0].ext.length'),0);run("S.mates[0].swapRules.maxHours=12.5");assert.equal(run('coverCalc().rows[0].ext.length'),1);run("w.codes.push({code:'Q',label:'Long',type:'work',start:'07:00',end:'20:00'})");assert.ok(run("colleagueLimit(w,S.mates[0],'Q',date)"));});
test('a clear D-only pattern is suggested without silently filtering by default',async()=>{const {run,runAsync}=pattern(seed());assert.equal(run("colleaguePattern(w,S.mates[0],date).codes.join(',')"),'D');run("S.shifts[0].text='E';S.shifts[0].segs=makeSegs(date,parse(w,'E'))");assert.equal(run('coverCalc().rows[0].free.length'),1);run('w.autoPatterns=true');assert.equal(run('coverCalc().rows[0].free.length'),0);assert.equal(run('coverCalc().rows[0].blocked[0].reason'),'preference');});
test('pattern learning ignores unreadable and unreviewed cells and requires sufficient evidence',async()=>{const {run,runAsync}=pattern(seed());run("S.mates[0].cells['2099-10-22']='E';S.mates[0].uns=['2099-10-22']");assert.equal(run("colleaguePattern(w,S.mates[0],date).codes[0]"),'D');run('S.mates[0].uns=[]');assert.equal(run('colleaguePattern(w,S.mates[0],date)'),null);run("S.mates[0].cells=Object.fromEntries(Array.from({length:19},(_,i)=>[rosterDate('2099-10-01',i),'D']))");assert.equal(run('colleaguePattern(w,S.mates[0],date)'),null);run("S.mates[0].cells=Object.fromEntries(Array.from({length:30},(_,i)=>[rosterDate('2099-10-01',i),i<7?'D':'-']))");assert.equal(run('colleaguePattern(w,S.mates[0],date)'),null)});
test('combined-only rosters are not used to infer an atomic duty restriction',async()=>{const {run,runAsync}=pattern(seed());run("for(const d of Object.keys(S.mates[0].cells))S.mates[0].cells[d]='DE'");assert.equal(run('colleaguePattern(w,S.mates[0],date)'),null)});
test('old patterns do not automatically constrain a distant future roster',async()=>{const {run,runAsync}=pattern(seed());run('w.autoPatterns=true');assert.equal(run("colleaguePattern(w,S.mates[0],'2100-01-01')"),null);assert.equal(run("colleagueLimit(w,S.mates[0],'E','2100-01-01')"),'')});
test('explicit choices and flexible override win over automatic patterns without bypassing manual limits',async()=>{const {run,runAsync}=pattern(seed());run('w.autoPatterns=true;S.mates[0].swapRules={allowed:["E"]}');assert.equal(run("colleagueLimit(w,S.mates[0],'E',date)"),'');run('S.mates[0].swapRules={ignorePattern:true,noCombined:true}');assert.equal(run("colleagueLimit(w,S.mates[0],'E',date)"),'');assert.ok(run("colleagueLimit(w,S.mates[0],'DE',date)"));});
test('hospital aliases are canonicalized in accepted shift rules',async()=>{const {run,runAsync}=seed();run("w.codes.find(c=>c.code==='D').aliases=['d'];S.mates[0].swapRules={allowed:['d']}");assert.equal(run('coverCalc().rows[0].free.length'),1)});
test('an explicit empty allowed list offers no working shifts, while null restores all',async()=>{const {run,runAsync}=seed();run('S.mates[0].swapRules={allowed:[]}');assert.equal(run('coverCalc().rows[0].free.length'),0);run('S.mates[0].swapRules.allowed=null');assert.equal(run('coverCalc().rows[0].free.length'),1)});
test('saved preference and automatic-filter changes are persistent-state fields and undoable',async()=>{const {run,runAsync}=seed();await runAsync("await updateColleagueRules('m',{excluded:true});S=JSON.parse(JSON.stringify(S))");assert.equal(run('S.mates[0].swapRules.excluded'),true);await run('undoLastChange()');assert.equal(run('S.mates[0].swapRules'),undefined);await runAsync("await setPatternFiltering('w1',true)");assert.equal(run('S.wps[0].autoPatterns'),true);await run('undoLastChange()');assert.equal(run('S.wps[0].autoPatterns'),undefined)});
test('colleague preferences are scoped by workplace and remain when roster cells are replaced',async()=>{const {run,runAsync}=seed();run("S.mates[0].swapRules={allowed:['D']};S.mates.push({...S.mates[0],id:'m2',wp:'w2',swapRules:{excluded:true}});Object.assign(S.mates[0].cells,{[date]:'E'})");assert.equal(run('mates(w.id).length'),1);assert.equal(run('S.mates[0].swapRules.allowed[0]'),'D')});
test('inline edits preserve draft values on same-page renders, fold freely and clear on navigation',async()=>{const {run,runAsync,document}=seed();run("tab='agenda';render();editShift('d');document.querySelector('#fc').value='E';document.querySelector('#inline-editor').open=false;render()");assert.equal(document.querySelector('#fc').value,'E');assert.equal(document.querySelector('#inline-editor').open,false);assert.equal(document.querySelector('#dlg').open,false);run('closeDialog()');assert.equal(document.querySelector('#inline-editor'),null);assert.equal(run('S.shifts[0].text'),'D');run("editShift('d');go('today')");assert.equal(document.querySelector('#inline-editor'),null)});
test('starting a second inline editor leaves one tool and one copy of each field',async()=>{const {run,runAsync,document}=seed();run("editShift('d');editMateCell('m',date)");assert.equal(document.querySelectorAll('#inline-editor').length,1);assert.equal(document.querySelectorAll('#fc').length,0);assert.equal(document.querySelectorAll('#mate-code').length,1)});
test('a changed colleague preference invalidates a formerly valid saved exchange preview',async()=>{const {run,runAsync}=seed();run("var ds=['2099-10-20','2099-10-21','2099-10-22','2099-10-23'];S.shifts=['D','N','-','-'].map((text,i)=>({id:'h'+i,wp:w.id,date:ds[i],text,segs:makeSegs(ds[i],parse(w,text))}));S.mates[0].cells=Object.fromEntries(['D','-','N','-'].map((t,i)=>[ds[i],t]));exchangePreview('h1','m',ds[2]);S.mates[0].swapRules={excluded:true}");const before=run('JSON.stringify(S)');await run("saveExchange('h1','m',ds[2])");assert.equal(run('JSON.stringify(S)'),before)});
test('manual limits affect trip cover candidates because they share the matching engine',async()=>{const {run,runAsync}=seed();run("S.mates[0].swapRules={excluded:true};S.rosterDays=Object.fromEntries(Array.from({length:40},(_,i)=>['w1|'+rosterDate('2099-10-01',i),true]))");assert.equal(run("tripCalc({days:2,from:'2099-10-19'}).swaps.every(s=>s.people.length===0)"),true)});
test('colleague manager exposes filters, readable observed evidence and persistent manual controls',async()=>{const {run,runAsync,document}=pattern(seed());run('openColleagues()');assert.equal(document.querySelectorAll('.colleague-card').length,1);assert.match(document.querySelector('#v').textContent,/الگوی برنامه/);assert.match(document.querySelector('#v').textContent,/فقط همین شیفت‌ها/);assert.equal(document.querySelector('#dlg').open,false)});
test('undo of colleague preferences keeps selected shifts that still exist',async()=>{const {run,runAsync}=seed();await runAsync("await updateColleagueRules('m',{excluded:true})");await run('undoLastChange()');assert.equal(run("tc.dates.join(',')"),'d')});
test('an inline tool attached inside a folded section is mounted outside the folded parent',async()=>{const {run,runAsync,document}=seed();run("document.querySelector('#v').innerHTML='<details id=folded><summary>Selection</summary><section class=calendar-panel></section></details>';showInline('<h3>Event</h3><input id=tool>', '.calendar-panel')");assert.equal(document.querySelector('#inline-editor').parentElement.id,'v');assert.equal(document.querySelector('#folded').contains(document.querySelector('#inline-editor')),false)});
test('accepted-shift chips reflect an active pattern and manual changes override it',async()=>{const {run,runAsync}=pattern(seed());run('w.autoPatterns=true');assert.equal(run("effectiveAllowedShifts(w,S.mates[0]).join(',')"),'D');await runAsync("await toggleAllowedShift('m','E')");assert.equal(run("S.mates[0].swapRules.allowed.join(',')"),'D,E');assert.equal(run("colleagueLimit(w,S.mates[0],'E',date)"),'')});
test('choosing all accepted shifts explicitly overrides automatic filtering',async()=>{const {run,runAsync}=pattern(seed());await runAsync("w.autoPatterns=true;await allowAllShifts('m')");assert.equal(run('S.mates[0].swapRules.ignorePattern'),true);assert.equal(run('S.mates[0].swapRules.allowed'),null);assert.equal(run("colleagueLimit(w,S.mates[0],'E',date)"),'')});
