const {test}=require('node:test'),assert=require('node:assert/strict'),{app}=require('./support.cjs');
function seed(){const a=app();a.run(`S.cal='g';var w=S.wps[0],date='2099-10-10';S.myname='برنامهٔ من';S.shifts=[{id:'off',wp:w.id,date,text:'-',segs:[]}];S.mates=['D','E','DE','N','EN','En','-','M','S'].map((text,i)=>({id:'m'+i,wp:w.id,name:'همکار '+i,cells:{[date]:text},uns:[],page:Math.floor(i/2)+1}));roster.wp=w.id;roster.cm=new Date('2099-10-01');roster.page=1;roster.date=date;roster.shift='E';tab='roster';render()`);return a}
test('off users can find every E colleague across pages including DE and EN',()=>{const {run}=seed();assert.equal(run("rosterPresence(w,date,'E').present.map(m=>m.id).join(',')"),'m1,m2,m4,m5');assert.equal(run('S.shifts[0].text'),'-');assert.equal(run("rosterPresence(w,date,'D').present.map(m=>m.id).join(',')"),'m0,m2')});
test('combined and short-night duties use components and full time coverage without handover-only matches',()=>{const {run}=seed();assert.equal(run("rosterPresence(w,date,'N').present.map(m=>m.id).join(',')"),'m3,m4');assert.equal(run("rosterShiftMatches(w,date,'E','D')"),false);assert.equal(run("rosterShiftMatches(w,date,'En','N')"),false);assert.equal(run("rosterShiftMatches(w,date,'EN','n')"),true);assert.equal(run("rosterPresence(w,date,'DE').present.map(m=>m.id).join(',')"),'m2')});
test('off, leave and stale off segments cannot become working staff',()=>{const {run}=seed();assert.equal(run("rosterShiftMatches(w,date,'-','D',makeSegs(date,parse(w,'D')))"),false);run("S.shifts[0].segs=makeSegs(date,parse(w,'D'))");assert.equal(run("rosterPresence(w,date,'D').present.some(p=>p.self)"),false);for(const code of ['-','M','S'])assert.equal(run(`rosterShiftMatches(w,date,${JSON.stringify(code)},'E')`),false)});
test('uncertain, missing and unknown codes are separately listed instead of asserted as present',()=>{const {run,document}=seed();run("S.mates[1].uns=[date];delete S.mates[2].cells[date];S.mates[4].cells[date]='?';render()");assert.equal(run("rosterPresence(w,date,'E').present.map(m=>m.id).join(',')"),'m5');assert.equal(run("rosterPresence(w,date,'E').unclear.map(m=>m.id).join(',')"),'m1,m2,m4');assert.equal(document.querySelectorAll('.presence-unclear li').length,3)});
test('presence ignores shift-swap restrictions and roster name search',()=>{const {run,document}=seed();run("S.mates[1].swapRules={excluded:true,allowed:['D']};roster.search='همکار 0';render()");assert.equal(document.querySelectorAll('.roster-table tbody tr').length,2);assert.equal(document.querySelectorAll('.presence-person').length,4);assert.equal(run("rosterPresence(w,date,'E').present.some(p=>p.id==='m1')"),true)});
test('lookup works without a personal row and cannot include colleagues from another workplace',()=>{const {run}=seed();run("S.shifts=[];S.mates.push({id:'other',wp:'w2',name:'Other',cells:{[date]:'E'},uns:[]})");assert.equal(run("rosterPresence(w,date,'E').present.length"),4);assert.equal(run("rosterPresence(w,date,'E').present.some(p=>p.id==='other')"),false)});
test('working users appear once and multiple personal duties can cover a combined query',()=>{const {run}=seed();run("S.shifts=['D','E'].map((text,i)=>({id:'own'+i,wp:w.id,date,text,segs:makeSegs(date,parse(w,text))}))");assert.equal(run("rosterPresence(w,date,'DE').present.filter(p=>p.self).length"),1);run('S.shifts[1].review=true');assert.equal(run("rosterPresence(w,date,'E').present.some(p=>p.self)"),false);assert.equal(run("rosterPresence(w,date,'E').unclear.filter(p=>p.self).length"),1)});
test('custom aliases and a dedicated combined shift are matched by their workplace hours',()=>{const {run}=seed();run("w.codes.push({code:'X',label:'Long duty',type:'work',start:'07:30',end:'20:00',aliases:['روزکامل']});S.mates.push({id:'custom',wp:w.id,name:'Custom',cells:{[date]:'روزکامل'},uns:[]})");assert.equal(run("rosterPresence(w,date,'E').present.some(p=>p.id==='custom')"),true);assert.equal(run("rosterPresence(w,date,'DE').present.some(p=>p.id==='custom')"),true);assert.equal(run("rosterWorkChoices(w).some(c=>c.code==='X')"),true)});
test('selection uses all month dates and keeps the seven-day roster preview in sync',()=>{const {run,document}=seed();run("selectRosterDate('2099-10-25')");assert.equal(run('roster.page'),3);assert.equal(run('roster.date'),'2099-10-25');assert.equal(document.querySelectorAll('.roster-date[aria-pressed=true]').length,1);run('moveRosterWeek(1)');assert.equal(run('roster.date'),'2099-10-31');run('moveRosterMonth(1)');assert.equal(run('roster.date'),'2099-11-01');run("selectRosterDate('2099-10-01')");assert.equal(run('roster.date'),'2099-11-01')});
test('every name is shown without show-more and escaped names and IDs cannot inject markup',()=>{const {run,document,context}=seed();context.bad=`<img src=x onerror=alert(1)>`;context.badId=`person'\"><svg>`;run("S.mates=Array.from({length:120},(_,i)=>({id:i===0?badId:'x'+i,wp:w.id,name:i===0?bad:'Person '+i,cells:{[date]:'E'},uns:[],page:Math.floor(i/20)+1}));render()");assert.equal(document.querySelectorAll('.presence-person').length,120);assert.equal(document.querySelectorAll('.roster-presence img,.roster-presence svg').length,0);assert.equal(document.querySelector('.presence-person').dataset.person,context.badId)});
test('lookup is read-only and automatic updates reflect edits and Undo',async()=>{const {run,document}=seed();const before=run('JSON.stringify(S)');run("selectRosterShift('D');selectRosterDate(date);render()");assert.equal(run('JSON.stringify(S)'),before);run("editMateCell('m1',date);$('#mate-code').value='D'");await run("saveMateCell('m1',date)");assert.equal(document.querySelectorAll('.presence-person').length,3);await run('undoLastChange()');assert.equal(document.querySelectorAll('.presence-person').length,2)});
test('disjoint combined shifts retain separate ranges instead of pretending continuous duty',()=>{const {run,document}=seed();run("w.combos=['DN'];roster.shift='DN';render()");assert.equal(run("presenceIntervals(makeSegs(date,parse(w,'DN'))).length"),2);assert.match(document.querySelector('.presence-time').textContent,/\+/)});
test('switching workplaces keeps the selected month and date while changing staff and shift choices',()=>{const {run,document}=seed();run("S.wps.push({id:'w2',name:'Second',codes:decCodes('X|Long|07:30-20:00\\n-|off|off')});S.mates.push({id:'other',wp:'w2',name:'Second colleague',cells:{[date]:'X'},uns:[]});selectRosterWorkplace('w2')");assert.equal(run('roster.date'),'2099-10-10');assert.equal(run('roster.shift'),'X');assert.equal(run('iso(roster.cm)'),'2099-10-01');assert.equal(document.querySelectorAll('.presence-person').length,1);assert.equal(document.querySelector('.presence-person').dataset.person,'other');run("selectRosterWorkplace('bad')");assert.equal(run('roster.wp'),'w2')});
